authors = ["Simon Zheng <simon.zheng@mail.mcgill.ca>"]
name = "DOEVisualizer"
uuid = "2d0b7fc2-8e2c-414b-aa02-4942dc8346b8"
version = "0.1.0"

# [deps]
# CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
# DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
# GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

# [compat]
# # julia = "1.5"
